spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
#      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/recycling_heroes
    username: root
    password: root
#    url: jdbc:postgresql://${URL}/${DATABASE}
#    username: ${USER}
#    password: ${PASSWD}
